# Welcome to your prefect.yaml file! You can use this file for storing and managing
# configuration for deploying your flows. We recommend committing this file to source
# control along with your flow code.

# Generic metadata about this project
name: unsplash-photo-trends
prefect-version: 2.13.0

# build section allows you to manage and build docker images
build:
- prefect_docker.deployments.steps.build_docker_image:
    requires: prefect-docker>=0.3.1
    id: build-image
    dockerfile: auto
    image_name: europe-west3-docker.pkg.dev/unsplash-photo-trends/prefect-prod/prefect
    tag: 2.13.0-python3.10

# push section allows you to manage if and how this project is uploaded to remote locations
push:
- prefect_docker.deployments.steps.push_docker_image:
    requires: prefect-docker>=0.3.1
    image_name: '{{ build-image.image_name }}'
    tag: '{{ build-image.tag }}'

# pull section allows you to provide instructions for cloning this project in remote locations
pull:
- prefect.deployments.steps.set_working_directory:
    directory: /opt/prefect/unsplash-photo-trends

# the deployments section allows you to provide configuration for deploying flows
deployments:
- name: ingest-photos-gcs-prod
  version: null
  tags: []
  description: Flow to download photos from unsplash and store them in Google Cloud
    Storage Bucket
  entrypoint: src/prefect/ingest_photos_gcs.py:ingest_photos_gcs
  parameters:
    gcp_credential_block_name: unsplash-photo-trends-deployment-sa
    proxy_type: datacenter
    batch_size: 10
    total_record_size: 20
  work_pool:
    name: prod-vertex-ai-work-pool
    work_queue_name: null
    job_variables:
      image: '{{ build-image.image }}'
  schedule: null
